tokenizer:
  model_name: Salesforce/codet5-base
  padding_side: left
  truncation_side: right
  pad_token_as_eos_token: False

reward_fn:
  id: rouge
  args:
    rouge_type: "rougel"
  
datapool:
  id: my_data_pool
  args:
    prompt_prefix: ""

env:
  n_envs: 10
  args:
    max_prompt_length: 512
    max_episode_length: 100
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0

alg:
  id: ppo
  args: 
    n_steps: 512
    batch_size: 32
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 5
    ent_coef: 0.0
  kl_div:
    coeff: 0.01
    target_kl: 0.2
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: rl4lm_exps/rl4lm_experiment/model-lc
      apply_model_parallel: True
      prompt_truncation_side: "right"
      generation_kwargs:
        do_sample: True
        top_k: 100
        min_length: 50
        max_new_tokens: 100
    
train_evaluation:
  eval_batch_size: 10
  n_iters: 50
  eval_every: 10
  save_every: 1
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
#    - id: bert_score
#      args:
#        language: en
    # - id: bleurt
    #   args:
    #     config_name: bleurt-large-512
#    - id: diversity
#      args: {}
    # - id: summaCZS
    #   args:
    #     granularity: sentence
    #     use_ent: True
    #     use_con: False
    # - id: summaCConv
    #   args:
    #     granularity: sentence
  generation_kwargs:
    do_sample: False
    top_k: 0
    temperature: 1
    min_length: 10
    num_beams: 5
    max_new_tokens: 200

